// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'together';
const description = 'A tool to merge text/code files in a folder';
const version = '2.7.0';
const repository = 'https://github.com/insign/together';
const executables = '{tog: null}';
const environment = '{sdk: >=3.0.0 <4.0.0}';
const dependencies = '{args: ^2.4.2, glob: ^2.1.2, path: ^1.9.0, test: ^1.25.8}';
const devDependencies = '{yaml2dart: ^1.5.0}';
